// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background/index.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Hitokoto: typeof import('./src/components/Hitokoto/index.vue')['default']
    Links: typeof import('./src/components/Links/index.vue')['default']
    Message: typeof import('./src/components/Message/index.vue')['default']
    Music: typeof import('./src/components/Music/index.vue')['default']
    Player: typeof import('./src/components/Player/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Set: typeof import('./src/components/Set/index.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks/index.vue')['default']
    TimeCapsule: typeof import('./src/components/TimeCapsule/index.vue')['default']
    Weather: typeof import('./src/components/Weather/index.vue')['default']
  }
}
